In [17]:
import numpy as np
import pandas as pd

In [18]:
a = np.array([1,2,3])

In [19]:
a[-1]

3

In [20]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


In [21]:
a = np.array([0,1,2,3,4,5,6,7,8])

In [22]:
mean = np.mean(a)
mean

4.0

In [23]:
variance = np.var(a)
variance

6.666666666666667

In [24]:
std = np.std(a)
std

2.581988897471611

In [25]:
b = np.array([a[:3], a[3:6], a[6:]])
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
d ={}
d['mean'] = [np.mean(b, axis=0), np.mean(b, axis=1), np.mean(b.flatten())]
d['variance'] = [np.var(b, axis=0), np.var(b, axis=1), np.var(b.flatten())]
d['standard deviation'] = [np.std(b, axis=0), np.std(b, axis=1), np.std(b.flatten())]
d

{'mean': [array([3., 4., 5.]), array([1., 4., 7.]), 4.0],
 'variance': [array([6., 6., 6.]),
  array([0.66666667, 0.66666667, 0.66666667]),
  6.666666666666667],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  array([0.81649658, 0.81649658, 0.81649658]),
  2.581988897471611]}

In [28]:
np.mean(b, axis=1)

array([1., 4., 7.])